# -*- coding: utf-8 -*-
"""extra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CTFrSqd_HgrIe0JspZhlqmtDgE8VymkR
"""

pip install scikit-learn

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

house_sizes = np.array([550, 600, 650, 700, 750, 800, 850, 900, 950, 1000])
prices = np.array([300000, 410000, 530000, 510000, 540000, 610000, 730000, 760000, 830000, 860000])

import matplotlib.pyplot as plt

plt.scatter(house_sizes, prices, color = 'r', label = 'Data Points')
plt.xlabel('House Size')
plt.ylabel('Prices')
plt.title('House Prices vs. House Sizes')
plt.legend()
plt.grid(True)
plt.show()

"""Step 2 & 3"""

X = house_sizes.reshape(-1, 1)
print(X)

X_train, X_test, y_train, y_test = train_test_split(X, prices, test_size=0.2, random_state=42)
print(X_test)
print(y_test)

"""Step 4: fit model and predict outcomes"""

# create LR model
model = LinearRegression()

# train the model using the training data
model.fit(X_train, y_train)

# make predictions on the test data
y_pred = model.predict(X_test)

# formatting
formatted_X_test = ["%.2f" % x for x in X_test]
print(formatted_X_test)
formatted_y_pred = ["%.2f" % y for y in y_pred]
print(formatted_y_pred)

# equation of the LR model

#coefficients
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

#construct the equation string
equation = f"y = {model.coef_[0]} * X + {model.intercept_}"
print("Linear Regression Equation:", equation)

"""Step 5"""

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)

formatted_mse = "%.2f" % mse
print(f"Mean Squared Error: {formatted_mse}")

"""Step 6"""

# assume you have a single unseen data point represented as a list
unseen_data = float(input("Enter house size:"))

# reshape the unseen data to a 2D array
unseen_data_reshaped = np.array(unseen_data).reshape(-1, 1)

# predict the target value for the unseen data point
predicted_value = model.predict(unseen_data_reshaped)

# print the predicted value
print(f"Predicted Value(RM): {predicted_value[0]:.2f}")

"""Step 7

Store the model using joblib or pickle
"""

from joblib import dump, load

dump(model, 'linear_regression_model.joblib')

"""Load the model and predict"""

model = load('linear_regression_model.joblib')
user_input =  int(input("Enter house size:"))
input_array = np.array([user_input]).reshape(-1, 1)
predicted_price = model.predict(input_array)
print(f"Predicted Value(RM): {predicted_price[0]:.2f}")

